# Generated by Django 6.0.4 on 2026-04-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='mundial2026/logos/')),
                ('team', models.ImageField(upload_to='mundial2026/teams/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='mundial2026/players/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_player', to='album_mundial2026.team')),
            ],
        ),
    ]
