# Generated by Django 6.0.4 on 2026-04-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HopfieldMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weights', models.BinaryField()),
                ('dims', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HopfieldExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(help_text='Lista de floats (flattened array)')),
                ('result', models.JSONField(blank=True, null=True)),
                ('is_convergent', models.BooleanField(default=False)),
                ('epochs', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='hopfield/results/')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='neuralapi.hopfieldmachine')),
            ],
        ),
    ]
