server {
	listen 8081;
	server_name intranet.gabrielalban.net;

	root /var/www/galban;
	index intranet.html;

	location / {
		try_files $uri $uri/ =404;
	}

	access_log /var/log/nginx/intranet_access.log;
	error_log /var/log/nginx/intranet_error.log;
}
