server {
	listen 8082;
	server_name zeus.gabrielalban.net;

	root /var/www/galban;
	index zeus.html;

	location / {
		try_files $uri $uri/ =404;
	}

	access_log /var/log/nginx/zeus_access.log;
	error_log /var/log/nginx/zeus_error.log;
}
